Repository codestates-seb/seb40_main_009, pull requests merged in 2022-11, with the labels that each got.

#44 feat: challenge 관련 기본 세팅 설정
  .idea/.gitignore
  .idea/aws.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/main-project.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  server/wiselife/build.gradle
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengePostDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeResponseDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/repository/ChallengeRepository.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/exception/BusinessLogicException.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/response/SingleResponseDto.java
  server/wiselife/src/main/resources/application.yml
Labels: 🆕 feat, BE오영운🚌

#45 feat: 환경설정
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.jsx
  client/src/assets/img/test.js
  client/src/assets/test.js
  client/src/atoms/atoms.js
  client/src/components/ChallengeList/Challenge.jsx
  client/src/components/UserList/UserList.jsx
  client/src/index.jsx
  client/src/pages/ChallengeList.jsx
  client/src/pages/UserList.jsx
  client/src/style/common.css
Labels: FE한병주🚌

#47 fix: import 부분 주석처리
  client/src/App.jsx
  client/src/components/Common/Header.js
Labels: ⚒️ fix, FE심이서 :people_holding_hands:

#48 feat: order 테이블 추가 + 카카오페이 결제시스탬 구축 + 로깅 appender 기능추가
  server/.idea/.gitignore
  server/.idea/modules.xml
  server/.idea/server.iml
  server/.idea/vcs.xml
  server/wiselife/backup/error/error-2022-11-15.0.log
  server/wiselife/backup/info/info-2022-11-15.0.log
  server/wiselife/backup/warn/warn-2022-11-15.0.log
  server/wiselife/build.gradle
  server/wiselife/log/error/error-2022-11-14.log
  server/wiselife/log/error/error-2022-11-15.log
  server/wiselife/log/info/info-2022-11-14.log
  server/wiselife/log/info/info-2022-11-15.log
  server/wiselife/log/warn/warn-2022-11-14.log
  server/wiselife/log/warn/warn-2022-11-15.log
  server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
  server/wiselife/src/main/java/be/wiselife/order/dto/OrderDto.java
  server/wiselife/src/main/java/be/wiselife/order/entity/Order.java
  server/wiselife/src/main/java/be/wiselife/order/mapper/OrderMapper.java
  server/wiselife/src/main/java/be/wiselife/order/repository/OrderRepository.java
  server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
  server/wiselife/src/main/resources/application.yml
  server/wiselife/src/main/resources/console-appender.xml
  server/wiselife/src/main/resources/file-error-appender.xml
  server/wiselife/src/main/resources/file-info-appender.xml
  server/wiselife/src/main/resources/file-warn-appender.xml
  server/wiselife/src/main/resources/logback-spring.xml
Labels: 🆕 feat, BE김민섭🦧

#52 feat: Member 엔티티 기본기능 구현
  server/wiselife/src/main/java/be/wiselife/WiselifeApplication.java
  server/wiselife/src/main/java/be/wiselife/aop/DiscordWebhook.java
  server/wiselife/src/main/java/be/wiselife/aop/GlobalExceptionAdvice.java
  server/wiselife/src/main/java/be/wiselife/audit/TimeAudit.java
  server/wiselife/src/main/java/be/wiselife/audit/WriterAudit.java
  server/wiselife/src/main/java/be/wiselife/dto/ErrorResponse.java
  server/wiselife/src/main/java/be/wiselife/dto/ErrorResponseDto.java
  server/wiselife/src/main/java/be/wiselife/dto/MultiResponseDto.java
  server/wiselife/src/main/java/be/wiselife/dto/PageInfo.java
  server/wiselife/src/main/java/be/wiselife/dto/SingleResponseDto.java
  server/wiselife/src/main/java/be/wiselife/exception/BusinessLogicException.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/member/repository/MemberRepository.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
Labels: 🆕 feat, BE김유현🚌

#53 feat: test
  client/src/App.jsx
  client/src/components/ChallengeList/Challenge.jsx
  client/src/components/SearchResult/ChallengeResult.jsx
  client/src/components/SearchResult/UserResult.jsx
  client/src/pages/ChallengeList.jsx
  client/src/pages/SearchResult.jsx
  client/src/pages/UserList.jsx
  client/src/style/ChallengeList/ChllengeList.styled.jsx
Labels: 🆕 feat, FE한병주🚌

#55 feat:footer, mainpage틀 작업
  client/src/App.jsx
  client/src/components/Common/Footer.js
  client/src/components/Common/Footer.jsx
  client/src/components/Common/Header.jsx
  client/src/components/Common/MainPage.jsx
  client/src/style/Common/FooterStyle.jsx
  client/src/style/Common/MainPageStyle.jsx
Labels: 🆕 feat, FE심이서 :people_holding_hands:

#56 feat: footer, header 버튼 클릭시 페이지 이동 구현
  client/src/App.jsx
  client/src/components/Common/Footer.jsx
  client/src/components/Common/Header.jsx
  client/src/style/Common/FooterStyle.jsx
  client/src/style/Common/HeaderStyle.jsx
Labels: 🆕 feat, FE심이서 :people_holding_hands:

#58 feat: 결제페이지 구축
  client/.eslintrc.json
  client/db.json
  client/src/App.jsx
  client/src/components/OrderSheetList/OrderSheetInfo.jsx
  client/src/pages/MyProfilePage.jsx
  client/src/pages/OrderSheetPage.jsx
Labels: 🆕 feat, FE김은비🚌

#59 feat: Kakao Oauth2 로그인 구현 완료
  server/wiselife/build.gradle
  server/wiselife/log/error/error-2022-11-15.log
  server/wiselife/log/info/info-2022-11-15.log
  server/wiselife/log/warn/warn-2022-11-15.log
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
  server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
  server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
  server/wiselife/src/main/java/be/wiselife/security/SecurityConfiguration.java
  server/wiselife/src/main/java/be/wiselife/security/controller/OauthController.java
  server/wiselife/src/main/java/be/wiselife/security/dto/AccessTokenDto.java
  server/wiselife/src/main/java/be/wiselife/security/dto/LoginDto.java
  server/wiselife/src/main/java/be/wiselife/security/filter/MemberAuthenticationEntryPoint.java
  server/wiselife/src/main/java/be/wiselife/security/handler/MemberAccessDeniedHandler.java
  server/wiselife/src/main/java/be/wiselife/security/handler/MemberAuthenticationFailureHandler.java
  server/wiselife/src/main/java/be/wiselife/security/handler/MemberAuthenticationSuccessHandler.java
  server/wiselife/src/main/java/be/wiselife/security/principal/KakaoMemberinfo.java
  server/wiselife/src/main/java/be/wiselife/security/principal/OAuth2MemberInfo.java
  server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
  server/wiselife/src/main/java/be/wiselife/security/utils/CustomAuthorityUtils.java
  server/wiselife/src/main/resources/application-oauth.yml
  server/wiselife/src/main/resources/application.yml
  server/wiselife/src/main/resources/logback-spring.xml
Labels: 🆕 feat, ⚒️ fix, BE김민섭🦧

#60 feat: 챌린지, 유저, 검색결과 페이지 라우터 설정
  client/src/App.jsx
  client/src/components/ChallengeList/Challenge.jsx
  client/src/components/SearchResult/ChallengeResult.jsx
  client/src/components/SearchResult/UserResult.jsx
  client/src/components/UserList/UserList.jsx
  client/src/pages/ChallengeList.jsx
  client/src/pages/SearchResult.jsx
  client/src/pages/UserList.jsx
  client/src/style/ChallengeList/Challenge.styled.jsx
  client/src/style/ChallengeList/ChallengeList.styled.jsx
  client/src/style/ChallengeList/ChllengeList.styled.jsx
  client/src/style/Common/HeaderStyle.jsx
  client/src/style/SearchResult/SearchResult.styled.jsx
  client/src/style/UserList/UserList.styled.jsx
  client/src/style/common.css
Labels: 🆕 feat, FE한병주🚌

#61 feat: 메인페이지 틀 구현
  client/package-lock.json
  client/package.json
  client/public/img/banner.png
  client/public/img/smile.jpg
  client/src/assets/img/test.js
  client/src/assets/test.js
  client/src/components/Common/MainPage.jsx
  client/src/style/Common/MainPageStyle.jsx
Labels: 🆕 feat, FE심이서 :people_holding_hands:

#62 feat: 마이페이지 프로필 구현
  client/src/App.jsx
  client/src/components/ProfileList/ChartBar.jsx
  client/src/components/ProfileList/MyProfile.jsx
  client/src/pages/MyProfilePage.jsx
  client/src/pages/OrderSheetPage.jsx
Labels: 🆕 feat, FE김은비🚌

#64 style: 결제페이지, 마이페이지 프로필 css 수정
  client/src/components/OrderSheetList/OrderSheetInfo.jsx
  client/src/pages/OrderSheetPage.jsx
  client/src/style/OrderSheetListStyle/OrderSheetInfoStyle.jsx
  client/src/style/OrderSheetListStyle/OrderSheetPageStyle.jsx.jsx
Labels: 🖍style, FE김은비🚌

#67 fix: Jwt Token fixed, order is still fixing
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
  server/wiselife/src/main/java/be/wiselife/order/dto/OrderDto.java
  server/wiselife/src/main/java/be/wiselife/order/entity/Order.java
  server/wiselife/src/main/java/be/wiselife/order/mapper/OrderMapper.java
  server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
  server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
  server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
Labels: ⚒️ fix, BE김민섭🦧

#65 feat: 팔로워 조작, 회원 조회, 회원 수정에 로그인 검증 추가
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/follow/controller/FollowController.java
  server/wiselife/src/main/java/be/wiselife/follow/entity/Follow.java
  server/wiselife/src/main/java/be/wiselife/follow/service/FollowService.java
  server/wiselife/src/main/java/be/wiselife/image/entity/Image.java
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
Labels: 🆕 feat, BE김유현🚌

#66 feat: challenge 기본 crud 구현 완료
  .idea/uiDesigner.xml
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengePostDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeResponseDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/dto/ChallengeTalkDto.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/entity/ChallengeTalk.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/mapper/ChallengeTalkMapper.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/service/ChallengeTalkService.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/response/SingleResponseDto.java
Labels: 🆕 feat, BE오영운🚌

#68 style:메인페이지 디자인수정 및 추가
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Main/MainPage.jsx
  client/src/components/Main/SlideBanner.jsx
  client/src/style/Main/MainPageStyle.jsx
  client/src/style/Main/SlideStyle.jsx
Labels: 🖍style, 🆕 feat, FE심이서 :people_holding_hands:

#69 style: 결제페이지, 마이페이지 프로필 css 수정 및 그래프 애니메이션
  client/src/components/ProfileList/ChartBar.jsx
  client/src/components/ProfileList/MyProfile.jsx
  client/src/components/ProfileList/ProfileImage.jsx
  client/src/image/ProfilePicture.png
  client/src/pages/MyProfilePage.jsx
  client/src/style/MyProfilePageStyle/ChartBarStyle.jsx
  client/src/style/MyProfilePageStyle/MyProfilePageStyle.jsx
  client/src/style/MyProfilePageStyle/MyProfileStyle.jsx
  client/src/style/MyProfilePageStyle/ProfileImageStyle.jsx
  client/src/style/OrderSheetListStyle/OrderSheetPageStyle.jsx.jsx
Labels: 🖍style, FE김은비🚌

#70 fix: order logic
  server/wiselife/src/main/java/be/wiselife/audit/TimeAudit.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
  server/wiselife/src/main/java/be/wiselife/order/dto/OrderDto.java
  server/wiselife/src/main/java/be/wiselife/order/entity/Order.java
  server/wiselife/src/main/java/be/wiselife/order/mapper/OrderMapper.java
  server/wiselife/src/main/java/be/wiselife/order/repository/OrderRepository.java
  server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
  server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
Labels: ⚒️ fix, BE김민섭🦧

#72 feat: 챌린지 상세페이지 조회 댓글 출력 기능 추가
  .idea/compiler.xml
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/controller/ChallengeTalkController.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/dto/ChallengeTalkDto.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/entity/ChallengeTalk.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/mapper/ChallengeTalkMapper.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/repository/ChallengeTalkRepository.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/service/ChallengeTalkService.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
Labels: 🆕 feat

#73 feat: 멤버 프로필 사진 등록 로직 구현
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeCertImage.java
  server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeExamImage.java
  server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeRepImage.java
  server/wiselife/src/main/java/be/wiselife/image/entity/Image.java
  server/wiselife/src/main/java/be/wiselife/image/entity/MemberImage.java
  server/wiselife/src/main/java/be/wiselife/image/entity/ReviewImage.java
  server/wiselife/src/main/java/be/wiselife/image/repository/ImageRepository.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
  server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
Labels: 🆕 feat, BE김유현🚌

#74 feat: 마이페이지 도전 중 탭 구현
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxChallenge.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxChallengeList.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxLists.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxOrderList.jsx
  client/src/components/ProfileList/ProfileImage.jsx
  client/src/pages/MyProfilePage.jsx
  client/src/style/MyProfilePageStyle/MyProfileStyle.jsx
  client/src/style/MyProfilePageStyle/ProfileBoxListsStyle/ProfileBoxChallengeListStyle.jsx
  client/src/style/MyProfilePageStyle/ProfileBoxListsStyle/ProfileBoxChallengeStyle.jsx
  client/src/style/MyProfilePageStyle/ProfileBoxListsStyle/ProfileBoxListsStyle.jsx
  client/src/style/MyProfilePageStyle/ProfileBoxListsStyle/ProfileBoxOrderListStyle.jsx
Labels: 🆕 feat, FE김은비🚌

#76 fix: className수정 및 주석처리
  client/src/App.jsx
  client/src/components/Common/Footer.jsx
  client/src/components/Common/Header.jsx
  client/src/pages/ChallengeDetail.jsx
  client/src/pages/MainPage.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
  client/src/style/Common/HeaderStyle.jsx
Labels: 🖍style, ⚒️ fix, FE심이서 :people_holding_hands:

#78 feat: 챌린지 추가 페이지 기능 구현
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/atoms/atoms.js
  client/src/atoms/atoms.jsx
  client/src/components/AddChallenge/CreateAsk0.jsx
  client/src/components/AddChallenge/CreateAsk1.jsx
  client/src/components/AddChallenge/CreateAsk2.jsx
  client/src/components/AddChallenge/CreateAsk3.jsx
  client/src/components/AddChallenge/CreateChallenge.jsx
  client/src/index.jsx
  client/src/pages/AddChallenge.jsx
  client/src/pages/ChallengeList.jsx
  client/src/style/Common/FooterStyle.jsx
Labels: 🆕 feat, FE한병주🚌

#77 feat: 챌린지 도전중 페이지 구현중
  client/src/App.jsx
  client/src/pages/ChallengeDetail.jsx
  client/src/pages/DetailPage.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
  client/src/style/DetailPage/DetailPageStyle.jsx
Labels: 🆕 feat, FE심이서 :people_holding_hands:

#79 style: css 수정
  client/db.json
  client/src/components/OrderSheetList/OrderSheetInfo.jsx
  client/src/components/ProfileList/ChartBar.jsx
  client/src/components/ProfileList/MyProfile.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxChallenge.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxChallengeList.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxOrderList.jsx
  client/src/components/ProfileList/ProfileImage.jsx
  client/src/pages/MyProfilePage.jsx
  client/src/pages/OrderSheetPage.jsx
  client/src/style/MyProfilePageStyle/ChartBarStyle.jsx
  client/src/style/MyProfilePageStyle/MyProfilePageStyle.jsx
  client/src/style/MyProfilePageStyle/MyProfileStyle.jsx
  client/src/style/MyProfilePageStyle/ProfileBoxListsStyle/ProfileBoxChallengeListStyle.jsx
  client/src/style/MyProfilePageStyle/ProfileBoxListsStyle/ProfileBoxChallengeStyle.jsx
  client/src/style/MyProfilePageStyle/ProfileBoxListsStyle/ProfileBoxListsStyle.jsx
  client/src/style/MyProfilePageStyle/ProfileBoxListsStyle/ProfileBoxOrderListStyle.jsx
  client/src/style/MyProfilePageStyle/ProfileImageStyle.jsx
  client/src/style/OrderSheetListStyle/OrderSheetInfoStyle.jsx
  client/src/style/OrderSheetListStyle/OrderSheetPageStyle.jsx.jsx
  client/src/style/OrderSheetPageStyle/OrderSheetPageStyle.jsx.jsx
Labels: 🖍style, ⚒️ fix, FE김은비🚌

#82 docs: order, security 주석정리
  server/wiselife/build.gradle
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
  server/wiselife/src/main/java/be/wiselife/order/mapper/OrderMapper.java
  server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
  server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
  server/wiselife/src/main/java/be/wiselife/security/SecurityConfiguration.java
  server/wiselife/src/main/java/be/wiselife/security/controller/OauthController.java
  server/wiselife/src/main/java/be/wiselife/security/filter/MemberAuthenticationEntryPoint.java
  server/wiselife/src/main/java/be/wiselife/security/principal/OAuth2MemberInfo.java
  server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
  server/wiselife/src/main/resources/application.yml
  server/wiselife/src/main/resources/file-info-appender.xml
  server/wiselife/src/main/resources/firebase/wiselife-6e33f-firebase-adminsdk-ibzyg-20b00f1642.json
  server/wiselife/src/main/resources/logback-spring.xml
Labels: 📜 Docs, BE김민섭🦧

#81 feat: 챌린지 후기 생성, 수정 구현
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/challengereview/controller/ChallengeReviewController.java
  server/wiselife/src/main/java/be/wiselife/challengereview/dto/ChallengeReviewDto.java
  server/wiselife/src/main/java/be/wiselife/challengereview/entity/ChallengeReview.java
  server/wiselife/src/main/java/be/wiselife/challengereview/mapper/ChallengeReviewMapper.java
  server/wiselife/src/main/java/be/wiselife/challengereview/repository/ChallengeReviewRepository.java
  server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/controller/ChallengeTalkController.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/entity/ChallengeTalk.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/service/ChallengeTalkService.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
Labels: 🆕 feat, BE오영운🚌

#80 feat: 챌린지 예시 사진 등록 로직 구현
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeCertImage.java
  server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeExamImage.java
  server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeRepImage.java
  server/wiselife/src/main/java/be/wiselife/image/entity/Image.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
Labels: 🆕 feat, BE김유현🚌

#83 feat: 유저 데이터 테스트 및 css수정
  client/package-lock.json
  client/public/img/spinner.gif
  client/src/components/Loading/Loading.jsx
  client/src/components/Main/SlideBanner.jsx
  client/src/pages/DetailPage.jsx
  client/src/pages/MainPage.jsx
  client/src/style/LoadingStyle/LoadingStyle.jsx
  client/src/style/Main/MainPageStyle.jsx
  node_modules/.package-lock.json
Labels: 🆕 feat, FE심이서 :people_holding_hands:

#84 feat : 챌린지 참가 기능 추가
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/challengereview/controller/ChallengeReviewController.java
  server/wiselife/src/main/java/be/wiselife/challengereview/entity/ChallengeReview.java
  server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/entity/ChallengeTalk.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeCertImage.java
  server/wiselife/src/main/java/be/wiselife/image/entity/Image.java
  server/wiselife/src/main/java/be/wiselife/image/entity/ReviewImage.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/entity/MemberChallenge.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/repository/MemberChallengeRepository.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
Labels: 🆕 feat, BE김유현🚌

#86 feat: 챌린지상세페이지 데이터 통신 테스트
  client/src/pages/ChallengeDetail.jsx
Labels: 🆕 feat, FE심이서 :people_holding_hands:

#87 feat: 결제 성공, 실패, 지연 취소 컴포넌트 구축
  client/src/pages/PaymentLists/CancellationPayment.jsx
  client/src/pages/PaymentLists/DelayPayment.jsx
  client/src/pages/PaymentLists/FailedPayment.jsx
  client/src/pages/PaymentLists/SuccessPayment.jsx
Labels: 🆕 feat, FE김은비🚌

#88 feat: 챌린지 추가 페이지 유효성 검사
  client/src/App.jsx
  client/src/atoms/atoms.jsx
  client/src/components/AddChallenge/CreateAsk0.jsx
  client/src/components/AddChallenge/CreateAsk1.jsx
  client/src/components/AddChallenge/CreateAsk2.jsx
  client/src/components/AddChallenge/CreateAsk3.jsx
  client/src/components/CreateChallenge/CreateAsk1.jsx
  client/src/components/CreateChallenge/CreateAsk2.jsx
  client/src/components/CreateChallenge/CreateAsk3.jsx
  client/src/components/CreateChallenge/CreateAsk4.jsx
  client/src/components/CreateChallenge/CreateChallenge.jsx
  client/src/image/example.png
  client/src/pages/AddChallenge.jsx
  client/src/pages/ChallengeList.jsx
  client/src/pages/CreateChallenge.jsx
  client/src/style/CreateChallenge/Challenge.styled.jsx
Labels: 🆕 feat, FE한병주🚌

#90 fix: fixing cors error
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
  server/wiselife/src/main/java/be/wiselife/security/SecurityConfiguration.java
  server/wiselife/src/main/java/be/wiselife/security/controller/TokenController.java
  server/wiselife/src/main/java/be/wiselife/security/filter/JwtVerificationFilter.java
  server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
  server/wiselife/src/main/java/be/wiselife/security/utils/CustomAuthorityUtils.java
  server/wiselife/src/main/resources/application.yml
Labels: ⚒️ fix, BE김민섭🦧

#91 feat: 멤버의 챌린지 성공률 표시되게 구현
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/repository/MemberChallengeRepository.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
Labels: 🆕 feat, BE김유현🚌

#92 feat: jwt 권한 이용한 crud 허용 기능
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/challengereview/controller/ChallengeReviewController.java
  server/wiselife/src/main/java/be/wiselife/challengereview/dto/ChallengeReviewDto.java
  server/wiselife/src/main/java/be/wiselife/challengereview/entity/ChallengeReview.java
  server/wiselife/src/main/java/be/wiselife/challengereview/repository/ChallengeReviewRepository.java
  server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/controller/ChallengeTalkController.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/dto/ChallengeTalkDto.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/entity/ChallengeTalk.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/service/ChallengeTalkService.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
Labels: 🆕 feat, BE오영운🚌

#93 fix: conflict codes
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/security/SecurityConfiguration.java
Labels: BE

#94 fix:메인페이지 수정 및 이미지경로 변경
  client/public/img/banner.png
  client/src/App.jsx
  client/src/components/ChallengeList/Challenge.jsx
  client/src/components/Loading/Loading.jsx
  client/src/image/smile.jpg
  client/src/image/spinner.gif
  client/src/pages/MainPage.jsx
  client/src/style/Main/MainPageStyle.jsx
Labels: ⚒️ fix, FE심이서 :people_holding_hands:

#95 feat: axios base URL 설정
  client/src/components/OrderSheetList/OrderSheetInfo.jsx
  client/src/components/ProfileList/Badge.jsx
  client/src/components/ProfileList/MyProfile.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxLists.jsx
  client/src/index.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/MyProfilePage.jsx
  client/src/pages/OrderSheetPage.jsx
  client/src/style/MyProfilePageStyle/BadgeStyle.jsx
Labels: 🆕 feat, FE김은비🚌

#96 fix: 코드 수정
  client/src/components/Common/Header.jsx
  client/src/components/Loading/Loading.jsx
  client/src/components/Main/SlideBanner.jsx
  client/src/pages/ChallengeDetail.jsx
  client/src/pages/DetailPage.jsx
  client/src/style/Common/HeaderStyle.jsx
Labels: ⚒️ fix, FE심이서 :people_holding_hands:

#97 fix: 코드 수정
  client/src/atoms/atoms.jsx
  client/src/components/ChallengeList/Challenge.jsx
  client/src/components/CreateChallenge/CreateAsk1.jsx
  client/src/components/CreateChallenge/CreateAsk2.jsx
  client/src/components/CreateChallenge/CreateAsk3.jsx
  client/src/components/CreateChallenge/CreateAsk4.jsx
  client/src/components/CreateChallenge/CreateChallenge.jsx
  client/src/pages/ChallengeList.jsx
  client/src/pages/CreateChallenge.jsx
  client/src/pages/UserList.jsx
  client/src/style/ChallengeList/Challenge.styled.jsx
Labels: ✂ 리팩토링, ⚒️ fix, FE한병주🚌

#98 feat: 멤버챌린지 개인성공률 구현
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
Labels: 🆕 feat, BE김유현🚌

#99 feat: Refresh Token logic add
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/member/repository/MemberRepository.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
  server/wiselife/src/main/java/be/wiselife/security/SecurityConfiguration.java
  server/wiselife/src/main/java/be/wiselife/security/controller/TokenController.java
  server/wiselife/src/main/java/be/wiselife/security/filter/JwtVerificationFilter.java
  server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
  server/wiselife/src/main/resources/application-oauth.yml
  server/wiselife/src/main/resources/application.yml
Labels: 🆕 feat, BE김민섭🦧

#101 feat: 카테고리에 해당하는 챌린지들 조회 기능 추가
  server/wiselife/src/main/java/be/wiselife/audit/TimeAudit.java
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/repository/ChallengeRepository.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/challengereview/repository/ChallengeReviewRepository.java
  server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/mapper/ChallengeTalkMapper.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/repository/MemberChallengeRepository.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
Labels: 🆕 feat, BE오영운🚌

#102 fix: dummy data
  server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/security/controller/TokenController.java
Labels: ⚒️ fix, BE

#103 fix: dummy data & order singleDTO
  server/wiselife/src/main/java/be/wiselife/dto/MultiResponseDto.java
  server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
  server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
Labels: ⚒️ fix, BE김민섭🦧

#104 feat: 파일수정 및 검색창구현
  client/src/App.jsx
  client/src/components/Common/Footer.jsx
  client/src/components/Common/Header.jsx
  client/src/components/Dashboard/SlideBanner.jsx
  client/src/pages/ChallengeDetail.jsx
  client/src/pages/ChallengeDetailProgress.jsx
  client/src/pages/DashboardPage.jsx
  client/src/pages/DetailPage.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
  client/src/style/Common/FooterStyle.jsx
  client/src/style/Common/HeaderStyle.jsx
  client/src/style/Dashboard/DashboardPageStyle.jsx
  client/src/style/Dashboard/SlideStyle.jsx
  client/src/style/DetailPage/DetailPageStyle.jsx
Labels: 🆕 feat, ⚒️ fix, FE심이서 :people_holding_hands:

#105 feat: member routing
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Common/Header.jsx
  client/src/components/MemberList/MemberList.jsx
  client/src/components/SearchResult/MemberResult.jsx
  client/src/components/SearchResult/UserResult.jsx
  client/src/components/UserList/UserList.jsx
  client/src/index.jsx
  client/src/pages/ChallengeDetail.jsx
  client/src/pages/MemberList.jsx
  client/src/pages/SearchResult.jsx
  client/src/pages/UserList.jsx
  client/src/style/MemberList/MemberList.styled.jsx
Labels: 🆕 feat, FE한병주🚌

#106 fix: css 및 코드수정
  client/src/pages/DashboardPage.jsx
  client/src/style/Dashboard/DashboardPageStyle.jsx
Labels: 🖍style, ✂ 리팩토링, ⚒️ fix, FE심이서 :people_holding_hands:

#107 fix: 챌린지 리뷰 삭제 수정 & feat: 챌린지 검색 자동완성 기능 + 챌린지 검색 기능
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/repository/ChallengeRepository.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/challengereview/controller/ChallengeReviewController.java
  server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/service/ChallengeTalkService.java
  server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/entity/MemberChallenge.java
Labels: 🆕 feat, ⚒️ fix, BE오영운🚌

#108 fix : 챌린지 내 인증 경로 이슈 해결중
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
  server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeCertImage.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/entity/MemberChallenge.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
Labels: 🆕 feat, ⚒️ fix, BE김유현🚌

#109 feat: search member controller
  server/wiselife/build.gradle
  server/wiselife/src/main/java/be/wiselife/dto/AmountResponseDto.java
  server/wiselife/src/main/java/be/wiselife/dto/MultiResponseDto.java
  server/wiselife/src/main/java/be/wiselife/image/config/imageConfig.java
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/member/repository/MemberRepository.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
  server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
  server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
  server/wiselife/src/main/resources/application-oauth.yml
  server/wiselife/src/main/resources/application.yml
Labels: 🆕 feat, ⚒️ fix, BE김민섭🦧

#110 feat: 파일 수정 및 기능 추가
  client/src/App.jsx
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/ChallengeDetail/DdayFormatter.jsx
  client/src/components/ChallengeDetail/Modal.jsx
  client/src/pages/ChallengeDetail.jsx
  client/src/pages/ChallengeDetailProgress.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
  client/src/style/ChallengeDetailProgress/ModalStyle.jsx
Labels: 🖍style, 🆕 feat, FE심이서 :people_holding_hands:

#112 feat: 레벨업 기능 구현
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/entity/MemberChallenge.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
Labels: 🆕 feat, BE김유현🚌

#113 feat: S3 image setting & member image setting
  server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/image/config/imageConfig.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/image/service/S3UploadService.java
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
  server/wiselife/src/main/resources/application.yml
Labels: 🆕 feat, BE김민섭🦧

#111 fix: 코드 수정 및 api연결
  client/src/App.jsx
  client/src/components/ProfileList/ChartBar.jsx
  client/src/components/ProfileList/MyProfile.jsx
  client/src/components/ProfileList/ProfileBoxLists/BoxOrderList.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxLists.jsx
  client/src/index.jsx
  client/src/pages/EditProfilePage.jsx
  client/src/pages/MyProfilePage.jsx
  client/src/style/MyProfilePageStyle/MyProfilePageStyle.jsx
Labels: ⚒️ fix, FE김은비🚌

#114 fix: 챌린지 리스트 카테고리 & 필터 기능
  client/src/components/ChallengeList/Challenge.jsx
  client/src/components/Common/Header.jsx
  client/src/components/CreateChallenge/CreateAsk1.jsx
  client/src/components/CreateChallenge/CreateAsk2.jsx
  client/src/components/CreateChallenge/CreateAsk3.jsx
  client/src/components/CreateChallenge/CreateAsk4.jsx
  client/src/components/CreateChallenge/CreateChallenge.jsx
  client/src/index.jsx
  client/src/pages/ChallengeList.jsx
  client/src/pages/CreateChallenge.jsx
  client/src/pages/MemberList.jsx
Labels: ⚒️ fix, FE한병주🚌

#115 feat: 챌린지 진행률 구현
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
Labels: 🆕 feat, FE심이서 :people_holding_hands:

#116 feat: 검색기능 구현
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/Common/Header.jsx
Labels: 🆕 feat, FE심이서 :people_holding_hands:

#119 feat: scheduler 이용한 챌린지 성공률, 종료여부 수정 구현 및 오류 수정
  .idea/compiler.xml
  server/wiselife/build.gradle
  server/wiselife/src/main/java/be/wiselife/WiselifeApplication.java
  server/wiselife/src/main/java/be/wiselife/audit/TimeAudit.java
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/repository/ChallengeRepository.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/dto/ChallengeTalkDto.java
  server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
  server/wiselife/src/main/java/be/wiselife/image/config/imageConfig.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/order/dto/OrderDto.java
  server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
  server/wiselife/src/main/resources/application.yml
Labels: 🆕 feat, ⚒️ fix, BE오영운🚌

#117 feat: 다음레벨을 위한 경험치 퍼센 트 구현
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
Labels: 🆕 feat, BE김유현🚌

#120 fix: image upload function "챌린지생성"
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/image/service/S3UploadService.java
Labels: 🆕 feat, ✂ 리팩토링, ⚒️ fix, BE김민섭🦧

#121 fix: 검색결과 페이지 라우터 설정
  client/src/App.jsx
  client/src/components/Common/Header.jsx
  client/src/components/CreateChallenge/CreateAsk4.jsx
  client/src/components/SearchResult/ChallengeResult.jsx
  client/src/components/SearchResult/MemberResult.jsx
  client/src/pages/MemberList.jsx
  client/src/pages/SearchResult.jsx
  client/src/style/ChallengeList/Challenge.styled.jsx
Labels: ⚒️ fix, FE한병주🚌

#122 feat: 챌린지리스트 보여주기 및 챌린지 상세 이미지 보여주기
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/ChallengeDetail/ImageModal.jsx
  client/src/components/ChallengeDetail/Modal.jsx
  client/src/pages/DashboardPage.jsx
  client/src/style/ChallengeDetailProgress/ImageModalStyle.jsx
Labels: 🆕 feat, FE심이서 :people_holding_hands:

#123 feat : 마이페이지 내 도전리스트를 도전중과 도전완료로 구분해 서 응답하게 구현
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challengereview/dto/ChallengeReviewDto.java
  server/wiselife/src/main/java/be/wiselife/challengereview/mapper/ChallengeReviewMapper.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/dto/ChallengeTalkDto.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/entity/ChallengeTalk.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/mapper/ChallengeTalkMapper.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/service/ChallengeTalkService.java
  server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/entity/MemberChallenge.java
Labels: 🆕 feat, BE김유현🚌

#124 feat: image function update 챌린지컨트롤러
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
Labels: 🆕 feat, BE김민섭🦧

#125 fix: 챌린지 상세페이지 조회시 이미지 경로 안보이는 오류 해결
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
Labels: ⚒️ fix, BE김유현🚌

#127 feat: 챌린지 상세조회 시 review도 함께 출력하는 기능 추가 이외 mapper 오류 수정
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challengereview/repository/ChallengeReviewRepository.java
  server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
Labels: 🆕 feat, ⚒️ fix, BE오영운🚌

#126 feat: review image send logic change
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/challengereview/controller/ChallengeReviewController.java
  server/wiselife/src/main/java/be/wiselife/challengereview/dto/ChallengeReviewDto.java
  server/wiselife/src/main/java/be/wiselife/challengereview/mapper/ChallengeReviewMapper.java
  server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/image/service/S3UploadService.java
Labels: 🆕 feat, ⚒️ fix, BE김민섭🦧

#128 feat: 타이틀 & 탭 아이콘
  client/public/index.html
  client/public/log.ico
  client/src/components/ChallengeList/Challenge.jsx
  client/src/index.jsx
  client/src/pages/ChallengeList.jsx
  client/src/style/ChallengeList/Challenge.styled.jsx
  client/src/style/ChallengeList/ChallengeList.styled.jsx
Labels: 🖍style, 🆕 feat, FE한병주🚌

#129 feat: css수정 및 기능 구현
  client/package-lock.json
  client/package.json
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/ChallengeDetail/ImageModal.jsx
  client/src/components/Common/Header.jsx
  client/src/pages/DashboardPage.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
  client/src/style/ChallengeDetailProgress/ImageModalStyle.jsx
Labels: 🖍style, 🆕 feat, FE심이서 :people_holding_hands:

#130 feat: 로그인페이지
  client/src/App.jsx
  client/src/components/ChallengeList/Challenge.jsx
  client/src/components/Common/Header.jsx
  client/src/components/Login/KakaoLogin.jsx
  client/src/components/Login/KakaoLoginData.jsx
  client/src/components/ProfileList/MyProfile.jsx
  client/src/components/ProfileList/ProfileBoxLists/BoxOrderList.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxOrderList.jsx
  client/src/image/kakaoIcon.png
  client/src/image/kakaoSmall.png
  client/src/pages/EditProfilePage.jsx
Labels: 🆕 feat, FE김은비🚌

#131 fix: 로그인 api
  client/src/App.jsx
  client/src/components/Common/Header.jsx
  client/src/components/Login/KakaoLogin.jsx
  client/src/components/Login/KakaoLoginData.jsx
  client/src/index.jsx
Labels: ⚒️ fix, FE김은비🚌

#132 feat: 챌린지 만들기 post 기능
  client/src/components/CreateChallenge/CreateChallenge.jsx
  client/src/components/SearchResult/MemberResult.jsx
  client/src/index.jsx
  client/src/pages/MemberList.jsx
Labels: 🆕 feat, FE한병주🚌

#133 fix: kakao login logic
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/java/be/wiselife/security/controller/OauthController.java
  server/wiselife/src/main/resources/application-oauth.yml
Labels: ⚒️ fix, BE김민섭🦧

#134 fix: 맴버 이미지 로직 변경
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challengereview/controller/ChallengeReviewController.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
Labels: ⚒️ fix, BE김유현🚌

#136 feat: cicd basic function & fix: member search function
  server/wiselife/Scripts/kill_process.sh
  server/wiselife/Scripts/remove_before.sh
  server/wiselife/Scripts/run_process.sh
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/resources/appspec.yml
Labels: 🆕 feat, ⚒️ fix, BE김민섭🦧

#138 feat: 상금 관련 로직 구현
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/entity/MemberChallenge.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
  server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
Labels: 🆕 feat, BE오영운🚌

#139 fix: bash codes
  server/wiselife/src/main/resources/appspec.yml
Labels: BE김민섭🦧

#143 fix: 코드수정
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/ChallengeDetail/DdayFormatter.jsx
  client/src/components/ChallengeDetail/Modal.jsx
  client/src/components/Common/Footer.jsx
  client/src/components/Common/Header.jsx
  client/src/components/Dashboard/SlideBanner.jsx
  client/src/components/Loading/Loading.jsx
  client/src/components/Main/SlideBanner.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
Labels: ✂ 리팩토링, ⚒️ fix, FE심이서 :people_holding_hands:

#146 fix: member 검색 pagination 수정
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/member/repository/MemberRepository.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/resources/application.yml
Labels: ⚒️ fix, BE

#149 feat: dayjs 다운로드 및 이미지 받아오는것 구현
  client/package-lock.json
  client/package.json
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
Labels: 🆕 feat, FE심이서 :people_holding_hands:

#153 "feat: 로그인 전역"
  client/package-lock.json
  client/package.json
  client/src/components/Login/KakaoLogin.jsx
  client/src/components/Login/KakaoLoginData.jsx
  client/src/components/ProfileList/Badge.jsx
  client/src/components/ProfileList/MyProfile.jsx
  client/src/components/ProfileList/MyProfileBox/Badge.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxLists.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxOrderList.jsx
  client/src/components/ProfileList/ProfileImage.jsx
  client/src/index.jsx
  client/src/pages/EditProfilePage.jsx
  client/src/pages/MyProfilePage.jsx
  client/src/pages/OrderSheetPage.jsx
  client/src/pages/PaymentLists/CancellationPayment.jsx
  client/src/pages/PaymentLists/DelayPayment.jsx
  client/src/pages/PaymentLists/FailedPayment.jsx
  client/src/pages/PaymentLists/SuccessPayment.jsx
Labels: 🆕 feat, FE김은비🚌

#154 feat: 로그아웃 구현 및 검색창 수정
  client/src/components/Common/Header.jsx
Labels: 🆕 feat, FE심이서 :people_holding_hands:

#159 feat: 로그아웃 구현 및 검색창 수정
  client/src/App.jsx
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/ChallengeDetail/ImageModal.jsx
  client/src/components/Common/Header.jsx
  client/src/pages/challengeDetailPage.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
  client/src/style/Common/HeaderStyle.jsx
Labels: 🆕 feat, ⚒️ fix, FE심이서 :people_holding_hands:

#160 style: 헤더 css 수정 및 폰트 변경
  client/src/components/Common/Header.jsx
  client/src/pages/challengeDetailPage.jsx
  client/src/style/Common/HeaderStyle.jsx
  client/src/style/common.css
Labels: 🖍style, 🆕 feat, FE심이서 :people_holding_hands:

#168 feat: 도전 시작일 까지 최소인원 모으지 못할지 챌린지 종료 및 참가자에게 환급
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/dto/ChallengeTalkDto.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/mapper/ChallengeTalkMapper.java
  server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/entity/MemberChallenge.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
  server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
  server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
  server/wiselife/src/main/resources/application.yml
Labels: 🆕 feat, BE김유현🚌

#170 feat: 카카오페이 결제
  client/src/App.jsx
  client/src/components/KakaoPay/KakaoPayData.jsx
  client/src/components/KakaoPay/PaymentLists/CancellationPayment.jsx
  client/src/components/KakaoPay/PaymentLists/FailedPayment.jsx
  client/src/components/KakaoPay/PaymentLists/SuccessPayment.jsx
  client/src/components/OrderSheetList/OrderSheetInfo.jsx
  client/src/components/ProfileList/Follower.jsx
  client/src/components/ProfileList/MyProfile.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxOrderList.jsx
  client/src/index.jsx
  client/src/pages/EditProfilePage.jsx
  client/src/pages/MyProfilePage.jsx
  client/src/pages/OrderSheetPage.jsx
  client/src/pages/PaymentLists/CancellationPayment.jsx
  client/src/pages/PaymentLists/DelayPayment.jsx
  client/src/pages/PaymentLists/FailedPayment.jsx
  client/src/pages/PaymentLists/SuccessPayment.jsx
  client/src/style/KakaoPay/KakaoPayStyle.jsx
Labels: 🆕 feat, FE김은비🚌

#171 fix: 1130 merge 전 push
  client/.env
  client/src/App.jsx
  client/src/components/ChallengeDetail/Modal.jsx
  client/src/components/ChallengeList/Challenge.jsx
  client/src/components/CreateChallenge/CreateChallenge.jsx
  client/src/components/CreateChallenge/FirstQuestionSet.jsx
  client/src/components/MemberList/Member.jsx
  client/src/components/SearchResult/ChallengeResult.jsx
  client/src/components/SearchResult/MemberResult.jsx
  client/src/pages/AdminPage.jsx
  client/src/pages/ChallengeListPage.jsx
  client/src/pages/CreateChallengePage.jsx
  client/src/pages/MemberListPage.jsx
  client/src/style/CreateChallenge/Challenge.styled.jsx
  client/src/style/MemberList/MemberList.styled.jsx
Labels: 🖍style, 🆕 feat, ⚒️ fix, FE한병주🚌

#173 feat: 기능 구현 및 수정
  client/package-lock.json
  client/package.json
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/ChallengeDetail/DdayFormatter.jsx
  client/src/components/ChallengeDetail/ProgressBar.jsx
  client/src/components/Common/Header.jsx
  client/src/pages/challengeDetailPage.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
  client/src/style/ChallengeDetailProgress/ProgressBar.jsx
  client/src/style/Common/HeaderStyle.jsx
  client/src/style/common.css
Labels: 🖍style, 🆕 feat, FE심이서 :people_holding_hands:

#175 "fix: 1130 merge"
  client/.env
  client/package-lock.json
  client/package.json
  client/src/atoms/atoms.jsx
  client/src/components/CreateChallenge/CreateChallenge.jsx
  client/src/components/CreateChallenge/ThirdQuestionSet.jsx
  client/src/components/Login/KakaoLoginData.jsx
  client/src/index.jsx
  client/src/pages/DashboardPage.jsx
Labels: 🆕 feat, FE
