Repository codestates-seb/seb40_main_009, pull requests merged in 2022-12, with the labels that each got.

#179 feat: 기능추가 및 스타일변경
  client/package.json
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/Common/Header.jsx
  client/src/pages/DashboardPage.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
  client/src/style/Common/FooterStyle.jsx
  client/src/style/Common/HeaderStyle.jsx
  client/src/style/Dashboard/DashboardPageStyle.jsx
Labels: 🆕 feat, ⚒️ fix, FE심이서 :people_holding_hands:

#178 feat: 리프레시 토큰
  client/src/App.jsx
  client/src/components/KakaoPay/KakaoPayData.jsx
  client/src/components/KakaoPay/PaymentLists/FailedPayment.jsx
  client/src/components/KakaoPay/PaymentLists/SuccessPayment.jsx
  client/src/components/Login/KakaoLogin.jsx
  client/src/components/Login/Login.jsx
  client/src/components/ProfileList/MyProfile.jsx
  client/src/components/ProfileList/ProfileBoxLists/BoxOrderList.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxLists.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxOrderList.jsx
  client/src/pages/MyProfilePage.jsx
Labels: 🆕 feat, FE김은비🚌

#181 feat : 트랜잭션 추가
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
  server/wiselife/src/main/java/be/wiselife/challengetalk/service/ChallengeTalkService.java
  server/wiselife/src/main/java/be/wiselife/follow/service/FollowService.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/image/service/S3UploadService.java
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
  server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
  server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
  server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
  server/wiselife/src/main/resources/application.yml
Labels: 🆕 feat, BE김유현🚌

#182 feat: login AOP build
  server/wiselife/log/error/error-2022-11-30.log
  server/wiselife/log/info/info-2022-11-30.log
  server/wiselife/log/warn/warn-2022-11-30.log
  server/wiselife/src/main/java/be/wiselife/aop/LoginAspect.java
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/image/service/S3UploadService.java
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
  server/wiselife/src/main/resources/application.yml
Labels: 🆕 feat, BE김민섭🦧

#183 feat: 기능수정 및 구현
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/ChallengeDetail/ImageModal.jsx
  client/src/components/ChallengeDetail/Modal.jsx
  client/src/components/Common/Footer.jsx
  client/src/pages/DashboardPage.jsx
  client/src/pages/challengeDetailPage.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
  client/src/style/Common/FooterStyle.jsx
Labels: 🖍style, 🆕 feat, ⚒️ fix, FE심이서 :people_holding_hands:

#184 fix: 카카오페이
  client/.env
  client/src/components/KakaoPay/PaymentLists/SuccessPayment.jsx
  client/src/components/Login/KakaoLogin.jsx
  client/src/components/OrderSheetList/OrderSheetInfo.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxOrderList.jsx
  client/src/pages/EditProfilePage.jsx
  client/src/pages/MyProfilePage.jsx
Labels: ⚒️ fix, FE김은비🚌

#185 style: css수정
  client/src/components/Common/Header.jsx
Labels: 🖍style, FE심이서 :people_holding_hands:

#186 feat: 1201 첫 배포
  client/.env
  client/public/index.html
  client/src/atoms/atoms.jsx
  client/src/atoms/payment.jsx
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeList/Challenge.jsx
  client/src/components/CreateChallenge/CreateChallenge.jsx
  client/src/components/KakaoPay/PaymentLists/SuccessPayment.jsx
  client/src/components/Login/KakaoLogin.jsx
  client/src/pages/ChallengeListPage.jsx
  client/src/pages/MyProfilePage.jsx
  client/src/style/ChallengeList/Challenge.styled.jsx
Labels: 🆕 feat, FE, FE한병주🚌

#187 feat: 코드수정
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/Common/Header.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
Labels: 🆕 feat, ⚒️ fix, FE심이서 :people_holding_hands:

#188 fix : 생성할때 결제, 참가할때 결제 후 챌린지 생성, 참가 되게 변경
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
  server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
  server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
Labels: 🆕 feat, BE김유현🚌

#190 fix: 스케줄러에 멀티스레드 적용하여 성능 향상
  server/wiselife/build.gradle
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
  server/wiselife/src/main/java/be/wiselife/schelduler/SchedulerConfig.java
  server/wiselife/src/main/resources/application.yml
Labels: 🆕 feat, ⚒️ fix, BE오영운🚌

#189 fix: setting and add listener and AOP sys added
  server/wiselife/build.gradle
  server/wiselife/src/main/java/be/wiselife/WiselifeApplication.java
  server/wiselife/src/main/java/be/wiselife/aop/GlobalExceptionAdvice.java
  server/wiselife/src/main/java/be/wiselife/aop/ServerDeployChecker.java
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/image/service/S3UploadService.java
  server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
  server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
  server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
  server/wiselife/src/main/java/be/wiselife/security/SecurityConfiguration.java
  server/wiselife/src/main/resources/application-aws.yml
Labels: 🆕 feat, ✂ 리팩토링, ⚒️ fix, BE김민섭🦧

#192 feat: 마이페이지 도전내역
  client/src/App.jsx
  client/src/components/ProfileList/MyProfile.jsx
  client/src/components/ProfileList/ProfileBoxLists/BoxOrderList.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxChallenge.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxChallengeList.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxLists.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxOrderList.jsx
  client/src/pages/MyProfilePage.jsx
  client/src/style/MyProfilePageStyle/ProfileBoxListsStyle/ProfileBoxListsStyle.jsx
Labels: 🆕 feat, ⚒️ fix, FE김은비🚌

#193 fix: 기능 수정
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/Common/Header.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
  client/src/style/Common/HeaderStyle.jsx
  client/src/style/Dashboard/DashboardPageStyle.jsx
Labels: ⚒️ fix, FE심이서 :people_holding_hands:

#194 fix: 결제 로직 변경
  client/src/atoms/atoms.jsx
  client/src/components/ChallengeList/Challenge.jsx
  client/src/components/Common/Header.jsx
  client/src/components/CreateChallenge/CreateChallenge.jsx
  client/src/components/CreateChallenge/SecondQuestionSet.jsx
  client/src/components/KakaoPay/PaymentLists/SuccessPayment.jsx
  client/src/components/OrderSheetList/OrderSheetInfo.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxOrderList.jsx
  client/src/pages/CreateChallengePage.jsx
Labels: ⚒️ fix, FE한병주🚌

#195 style: css수정
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/Common/Header.jsx
  client/src/pages/MyProfilePage.jsx
  client/src/pages/challengeDetailPage.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
  client/src/style/Common/HeaderStyle.jsx
Labels: 🖍style, ⚒️ fix, FE심이서 :people_holding_hands:

#198 fix: 카카오 환경변수 git actions에 추가
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
  server/wiselife/src/main/resources/application-aws.yml
  server/wiselife/src/main/resources/application.yml
Labels: ⚒️ fix, BE오영운🚌

#197 fix: 1225 머지
  client/src/components/Common/Header.jsx
  client/src/components/KakaoPay/PaymentLists/SuccessPayment.jsx
Labels: ⚒️ fix, FE한병주🚌

#204 fix: css및 기능 추가
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/Common/Header.jsx
  client/src/image/logo.jpg
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
  client/src/style/Common/HeaderStyle.jsx
Labels: ⚒️ fix, FE심이서 :people_holding_hands:

#211 fix : 결제 충전형태로 변경
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
  server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
  server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
  server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
  server/wiselife/src/main/java/be/wiselife/security/SecurityConfiguration.java
  server/wiselife/src/main/java/be/wiselife/security/dto/LoginDto.java
  server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
  server/wiselife/src/main/resources/application.yml
Labels: ⚒️ fix, BE김유현🚌

#210 fix: appender & eventlistener
  server/wiselife/build.gradle
  server/wiselife/src/main/java/be/wiselife/aop/ServerDeployChecker.java
  server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
  server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
  server/wiselife/src/main/resources/application-aws.yml
  server/wiselife/src/main/resources/console-appender.xml
  server/wiselife/src/main/resources/file-error-appender.xml
  server/wiselife/src/main/resources/file-info-appender.xml
  server/wiselife/src/main/resources/file-warn-appender.xml
  server/wiselife/src/main/resources/logback-spring.xml
Labels: ✂ 리팩토링, ⚒️ fix, BE김민섭🦧

#216 fix: point로 변경된 결제 방법
  client/.env
  client/src/atoms/atoms.jsx
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeList/Challenge.jsx
  client/src/components/Common/Header.jsx
  client/src/components/CreateChallenge/CreateChallenge.jsx
  client/src/components/CreateChallenge/SecondQuestionSet.jsx
  client/src/components/KakaoPay/PaymentLists/SuccessPayment.jsx
  client/src/components/Login/KakaoLogin.jsx
  client/src/components/OrderSheetList/OrderSheetInfo.jsx
  client/src/components/ProfileList/Follower.jsx
  client/src/components/ProfileList/MyProfile.jsx
  client/src/pages/MyProfilePage.jsx
  client/src/pages/OrderSheetPage.jsx
  client/src/style/KakaoPay/KakaoPayStyle.jsx
  client/src/style/OrderSheetPageStyle/OrderSheetPageStyle.jsx.jsx
Labels: 🆕 feat, ⚒️ fix, FE한병주🚌

#218 fix: settings about cloudwatch & order DTO
  server/wiselife/build.gradle
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
  server/wiselife/src/main/java/be/wiselife/order/dto/OrderDto.java
  server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
  server/wiselife/src/main/resources/application-aws.yml
  server/wiselife/src/main/resources/console-appender.xml
  server/wiselife/src/main/resources/logback-spring.xml
Labels: 🆕 feat, ✂ 리팩토링, ⚒️ fix, BE김민섭🦧

#219 fix: 회원수정시 이미지만 수정하는 상황 관련 오류 수정
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
  server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
Labels: ⚒️ fix, BE오영운🚌

#220 fix: 챌린지 참가금액 부족시 결제 로직 타게 변경
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
Labels: ⚒️ fix, BE김유현🚌

#217 refactor: 코드 정리
  client/src/App.jsx
  client/src/atoms/Profile.jsx
  client/src/components/KakaoPay/PaymentLists/CancellationPayment.jsx
  client/src/components/KakaoPay/PaymentLists/FailedPayment.jsx
  client/src/components/KakaoPay/PaymentLists/SuccessPayment.jsx
  client/src/components/Login/KakaoLogin.jsx
  client/src/components/Login/KakaoLoginData.jsx
  client/src/components/Login/Login.jsx
  client/src/components/OrderSheetList/OrderSheetInfo.jsx
  client/src/components/ProfileList/ChartBar.jsx
  client/src/components/ProfileList/Follower.jsx
  client/src/components/ProfileList/MyProfile.jsx
  client/src/components/ProfileList/MyProfileBox/Badge.jsx
  client/src/components/ProfileList/ProfileBoxLists/BoxOrderList.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxChallenge.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxChallengeList.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxLists.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxOrderList.jsx
  client/src/components/ProfileList/ProfileImage.jsx
  client/src/components/SearchResult/UserResult.jsx
  client/src/pages/ChallengeList.jsx
  client/src/pages/EditProfilePage.jsx
  client/src/pages/MyProfilePage.jsx
  client/src/pages/OrderSheetPage.jsx
  client/src/pages/SearchResult.jsx
  client/src/style/ChallengeList/ChllengeList.styled.jsx
  client/src/style/MyProfilePageStyle/BadgeStyle.jsx
  client/src/style/MyProfilePageStyle/EditProfileStyle.jsx
  client/src/style/MyProfilePageStyle/MyProfilePageStyle.jsx
  client/src/style/MyProfilePageStyle/ProfileBoxListsStyle/ProfileBoxListsStyle.jsx
  client/src/style/OrderSheetPageStyle/OrderSheetPageStyle.jsx.jsx
Labels: ✂ 리팩토링, FE김은비🚌

#222 fix: 기능 수정 및 css변경
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/Common/Header.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
Labels: ⚒️ fix, FE심이서 :people_holding_hands:

#223 fix: 좋아요 기능
  client/.env
  client/src/components/ProfileList/Follower.jsx
  client/src/components/ProfileList/ProfileImage.jsx
  client/src/pages/EditProfilePage.jsx
  client/src/pages/MyProfilePage.jsx
Labels: ⚒️ fix, FE김은비🚌

#225 fix: 동의하기 클릭안하면 결제버튼 막기
  client/src/pages/OrderSheetPage.jsx
  client/src/style/OrderSheetPageStyle/OrderSheetPageStyle.jsx.jsx
Labels: ⚒️ fix, FE심이서 :people_holding_hands:

#226 fix: 챌린지 완료시 완료글 추가 및 css수정
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/ChallengeDetail/DdayFormatter.jsx
  client/src/components/Common/Header.jsx
Labels: ⚒️ fix, FE심이서 :people_holding_hands:

#227 style: 해더 css수정
  client/src/components/Common/Header.jsx
Labels: 🖍style, FE심이서 :people_holding_hands:

#228 fix: 검색창 엔터키
  client/src/components/Common/Header.jsx
Labels: ⚒️ fix, FE심이서 :people_holding_hands:

#229 fix: 좋아요 기능
  client/src/components/ProfileList/Follower.jsx
  client/src/components/ProfileList/MyProfile.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxChallenge.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxOrderList.jsx
Labels: ⚒️ fix, FE김은비🚌

#230 fix: 주문내역 확인
  client/src/components/ProfileList/ProfileBoxLists/BoxOrderList.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxOrderList.jsx
Labels: ⚒️ fix, FE김은비🚌

#232 fix: scheduler 주기 변동
  server/wiselife/src/main/java/be/wiselife/challengereview/entity/ChallengeReview.java
  server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
  server/wiselife/src/main/java/be/wiselife/schelduler/SchedulerConfig.java
Labels: BE

#231 fix: 마이페이지 수정
  client/src/components/ProfileList/ProfileImage.jsx
  client/src/pages/EditProfilePage.jsx
Labels: ⚒️ fix, FE김은비🚌

#233 fix: 유료챌린지 참가시 상세페이지로 이동
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
Labels: ⚒️ fix, FE심이서 :people_holding_hands:

#234 fix: validation 설정 완료
  client/.env
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/ChallengeList/Challenge.jsx
  client/src/components/Common/Header.jsx
  client/src/components/CreateChallenge/CreateChallenge.jsx
  client/src/components/CreateChallenge/FirstQuestionSet.jsx
  client/src/components/CreateChallenge/ThirdQuestionSet.jsx
  client/src/components/ProfileList/ProfileBoxLists/ProfileBoxChallenge.jsx
  client/src/pages/ChallengeList.jsx
  client/src/pages/ChallengeListPage.jsx
  client/src/pages/MemberListPage.jsx
  client/src/pages/OrderSheetPage.jsx
  client/src/style/CreateChallenge/Challenge.styled.jsx
Labels: 🆕 feat, ⚒️ fix, FE한병주🚌

#235 fix:log setting
  server/wiselife/src/main/java/be/wiselife/aop/LoginAspect.java
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/resources/application.yml
  server/wiselife/src/main/resources/logback-spring.xml
Labels: BE김민섭🦧

#236 fix: 환급금 및 진행률 음수로 나오는 버그 해결 및 member 수정 로직 변경
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
  server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
  server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
Labels: ⚒️ fix, BE오영운🚌

#237 ix : 챌린지 참가/탈퇴시 포인트 변경되게 수정, 챌린지내 최소인원, 최대인원, 최소 참가 금 벨리데이션 추가
  server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
  server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
  server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
Labels: ⚒️ fix, BE김유현🚌

#240 fix: 유저리스트 css수정
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/MemberList/Member.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
  client/src/style/MemberList/MemberList.styled.jsx
Labels: 🖍style, ⚒️ fix, FE심이서 :people_holding_hands:

#241 fix: 1205 수정
  client/.env
  client/src/App.jsx
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/CreateChallenge/FourthQuestionSet.jsx
  client/src/components/CreateChallenge/SecondQuestionSet.jsx
  client/src/components/CreateChallenge/ThirdQuestionSet.jsx
  client/src/pages/SearchResult.jsx
  client/src/style/ChallengeList/ChllengeList.styled.jsx
Labels: ⚒️ fix, FE한병주🚌

#245 fix: 토큰 재발급 & 자동 로그아웃 & 이미지 사이즈 체크 & 스타일
  client/.env
  client/src/components/ChallengeList/Challenge.jsx
  client/src/components/Common/Header.jsx
  client/src/components/CreateChallenge/CreateChallenge.jsx
  client/src/components/CreateChallenge/FirstQuestionSet.jsx
  client/src/components/CreateChallenge/FourthQuestionSet.jsx
  client/src/components/CreateChallenge/SecondQuestionSet.jsx
  client/src/components/CreateChallenge/ThirdQuestionSet.jsx
  client/src/components/Login/KakaoLogin.jsx
  client/src/function/checkImageSize.jsx
  client/src/pages/ChallengeListPage.jsx
  client/src/pages/CreateChallengePage.jsx
  client/src/pages/EditProfilePage.jsx
  client/src/pages/MemberListPage.jsx
  client/src/style/ChallengeList/ChallengeList.styled.jsx
  client/src/style/CreateChallenge/Challenge.styled.jsx
Labels: 🖍style, ⚒️ fix, FE한병주🚌

#246 fix: 참여하기 당일에도 참가가능, 인증시가표시, 도전유저 이름 css 수정
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
Labels: 🖍style, ⚒️ fix, FE심이서 :people_holding_hands:

#247 feat: 해더 url링크추가
  client/src/components/Common/Header.jsx
Labels: 🆕 feat, FE심이서 :people_holding_hands:

#248 style: css변경
  client/src/components/Common/Header.jsx
Labels: 🖍style, FE심이서 :people_holding_hands:

#250 feat: demoday용 깜짝이벤트 챌린지 로직 추가
  server/wiselife/src/main/java/be/wiselife/WiselifeApplication.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/resources/logback-spring.xml
Labels: 🆕 feat, ⚒️ fix, BE오영운🚌

#251 fix : 챌린지 인증사진 동일 시간대 등록시 최근 등록한걸로 수정되게 수정
  server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
  server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
  server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
  server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
Labels: ⚒️ fix, BE김유현🚌

#252 style: 챌린지 상세페이지 css
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/components/Common/Header.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
Labels: 🖍style, FE심이서 :people_holding_hands:

#254 style:메인페이지 css 수정
  client/src/pages/DashboardPage.jsx
  client/src/style/Dashboard/DashboardPageStyle.jsx
Labels: 🖍style, FE심이서 :people_holding_hands:

#256 fix: demoday용 챌린지가 모든 로직 타는 것 수정
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
Labels: ⚒️ fix, BE

#253 fix: merge 후 챌린지내 멤버 금일 인증횟수 표시 구현
  server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
Labels: ⚒️ fix, BE김유현🚌

#257 fix: challenge수정 로직 & scheduler 주기 변경
  server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
  server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
  server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
  server/wiselife/src/main/resources/logback-spring.xml
Labels: ⚒️ fix, BE오영운🚌

#262 style: 헤더 메뉴 스타일 변경
  client/src/style/Common/HeaderStyle.jsx
Labels: 🖍style, FE김은비🚌

#264 style:인라인스타일 스타일컴포넌트로 수정
  client/src/components/ChallengeDetail/ChallengeDetail.jsx
  client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
  client/src/pages/DashboardPage.jsx
  client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
  client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
  client/src/style/Dashboard/DashboardPageStyle.jsx
Labels: 🖍style, ✂ 리팩토링, FE심이서 :people_holding_hands:
